### ISSUE TITLE
sort out grounding...

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Kasli#10]

**Comment by jordens** [comment]
@hartytp details and context for this? clock or power or switcher or FPGA or panel?

**Comment by marmeladapk** [comment]
I think @hartytp meant what you outlined in #26.

**Comment by hartytp** [comment]
@jordens not sure why this doesn't have a description. Let's assume that what I meant was
1. Change default population options to avoid floating the MMCXs
2. Add RC components to allow the FP to be floated, but populate the R with 0R so that by default the FP is tied to circuit ground
3. Use nice FPs with EMC gaskets

Essentially, follow the same grounding strategy we're using in other boards now.

**Comment by jordens** [comment]
and ground the SMA input as well.

**Comment by jordens** [comment]
Let's implement the MMCX and SMA changes ASAP.

**Comment by marmeladapk** [comment]
a87c75c
