### ISSUE TITLE
PCA9548 failed to ack write address

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Kasli#15]
_From @hartytp on April 11, 2018 22:4_

One of my Kasli boards is now showing up this error on boot "panic at src/libcore/result.rs:906: cannot initialize Si5324: "PCA9548 failed to ack write address"

_Copied from original issue: sinara-hw/sinara#540_

**Comment by gkasprow** [comment]
Was this PCA9548 failed last time? How did Technosystem repaired it? They replaced this chip?
Did it die just itself or after configuration of boards changed?

**Comment by hartytp** [comment]
Sorry, I wasn't clear. This is a different Kasli (TechnoSystem replaced the old one with a Kasli v1.1 with higher speed-grade FPGA).

I think the board configuration was changed.

**Comment by gkasprow** [comment]
ESD is one issue, mains filter EMC filter capacitors charge is another issue that can kill such chip
