### ISSUE TITLE
BNX022 soldering issue

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Kasli#17]
Sometimes the solder blob on a BNX022 pad touches the component lead but does not wet it. This causes an unreliable connection and a nasty problem where a board passes tests but no longer powers on after shipping, as the vibrations broke the connection.
Might be a problem with the coating of the lead on some BNX022s as it is unusually difficult to make the solder wet when fixing it manually.

**Comment by gkasprow** [comment]
Can you take a photo and post it here please?

**Comment by sbourdeauducq** [comment]
It seems the coating is ok, the problem is the large metallic part connected to the ground pins inside the BNX022, which sinks heat (the problem happens on GND but I haven't seen it on +12V).

**Comment by hartytp** [comment]
@gkasprow what do we do about this?

**Comment by gkasprow** [comment]
There is already the thermal relief used for this part so we cannot do much from PCB design perspective.
One must pay attention during inspection and tests.

**Comment by hartytp** [comment]
Ack. I guess these kind of issues are best fed back directly to the manufacturer.
