### ISSUE TITLE
Ethernet stops working when multiple EEMs used

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Kasli#2]
@marmeladapk found that when multiple Urukul or other EEM are plugged, Ethernet does not work.
The same happens when Kasli is supplied via extension backplane board.
Did you observe such case?
We will investigate it.

**Comment by marmeladapk** [comment]
For example in suservo setup without dios link would not set up. On terminal no errors regarding ethernet are printed. It was a problem when 12V current was higher than ~1,5A.

**Comment by jordens** [comment]
I have configured more than a dozen systems and at least 6 of them had 8 EEMs (3 Urukul, 1 Zotino, 1 Sampler, 3 DIO). I haven't seen this. From the description it's unclear what exactly you tried and what your configuration is. You'll have to supply versions, numbers etc.

**Comment by gkasprow** [comment]
That's why I'm surprised that this occurred in my lab. Kasli was already tested with various configurations and so far nobody reported such effect.

**Comment by jordens** [comment]
And you are sure that the hardware, gatware, firmware, bootloader versions match and are what you expect? What about the rest of the Toolchain?

**Comment by hartytp** [comment]
@gkasprow @marmeladapk can you reproduce this, or can we close?

**Comment by hartytp** [comment]
Can we close this?
