### ISSUE TITLE
backplane adapter fastening

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Kasli#28]
Before Kasli 2.0, can we find a short-term solution to solidly attach backplane adapters to Kasli?
The friction from the connector + 220mm card guides is not enough. I had a crate where the adapter detached completely during shipping.

**Comment by gkasprow** [comment]
@sbourdeauducq you can use the edge connector mounting holes and thin plastic zip ties to fasten the backplane to the Kasli.
