### ISSUE TITLE
rotate SATA connector

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Kasli#29]

**Comment by marmeladapk** [comment]
This also requires rotating JTAG connector -- I'll switch it to surface mounted (same as in Sayma), otherwise it will block current in power planes on all layers.

**Comment by jordens** [comment]
What about ditching the JTAG connector? Is it important to keep it? Is it needed and used?

**Comment by marmeladapk** [comment]
Yes, for example during tests. Also you cannot use USB JTAG with Vivado (MIG and IBERT) (we'll try something with FTDI in the near future but we're not certain that it will work).

**Comment by jordens** [comment]
Ok.
But really? That would imply that you can't use the digilent castellated modules (which are just FTDI) on the standard dev kits (KC705...) with IBERT or MIG.

**Comment by marmeladapk** [comment]
Yes you can, however they have special ROM contents and are seen differently by Vivado. And these FTDIs on digilent modules are FT2232 not 4232.

**Comment by marmeladapk** [comment]
SATA connector will be rotated and placed above SFP cage.
