### ISSUE TITLE
move clock SMA

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Kasli#33]
> Move the clock input SMA further towards the panel. Leave just enough gap for the insulating washer. Otherwise (with a gap, the two insulating washers, the panel, and the nut, even without the springy/claw washer) there is not enough thread to fully tighten an SMA connector.

I see a similar issue on Urukul as well, where I am not able to fully tighten the SMAs on some cards unless I fiddle with the stackup.

Now that we're not floating grounds by default, should we just DNP these washers?

**Comment by jordens** [comment]
I don't think the plastic washers are the cause of the problem. And if the washers are gone, probably the hole would have to be smaller to properly counter the spring washer and nut. The smaller hole would then always prevent using the plastic washers and AC-coupling the shield. If there are no plastic washers, then the foil on the panel or anodizing will be likely be damaged by the standard metal spring/teeth washers. This would need to be considered. Also if we decide against the use of plastic washers, then we should go all the way and fully ground the shield without the use of 0R jumpers.
If this can be solved with getting the positioning and stackup right, then why not do that?

**Comment by gkasprow** [comment]
I managed to:
- move the SMA 0.75mm to the panel
- move the board edge to the panel, leave 0.5mm clearance
- increase the SMA hole diameter by 0.5mm
It should solve the issue.
