### ISSUE TITLE
move some signals to I2C extenders

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Kasli#38]
@marmeladapk 
> Here's the list of signals I'd like to move to I2C extenders (and route interrupt signals to the FPGA instead):
> - SFP 0,1,2 (TX_DISABLE, RATE_SELECT, RATE_SELECT1, TX_FAULT, MOD_PRESENT, LED, LOS)
> -led_user1-3
> - VUSB_PRESENT

@jordens 
> Ok moving the signals to an extender apart from the three SFP LEDs please. The other user_leds can go away.

**Comment by marmeladapk** [comment]
Additional signals: 
- Clock source select for AD948
- Main, Helper DCXO OE

There are 7 free pins. @jordens requested some additional FP leds, how many do you want?

**Comment by jordens** [comment]
I'd like at least one FP LED on a non-I2C pin directly on the FPGA. That LED doesn't need to be associated with a connector. This is really useful for debugging and status signalling on Kasli.
The other LEDs don't matter. One I2C LED per SFP port is fine IMO. Maybe another one associated to the SMA connector.

**Comment by marmeladapk** [comment]
@jordens You have 3 SFP LEDs on FP, is that enough or do you want additional one?

**Comment by jordens** [comment]
If they go directly to fpga pins then that's fine. if they go through i2c extenders, I'd like another fp led that goes directly to the fpga.

**Comment by marmeladapk** [comment]
You asked for SFP LEDs to go directly to the FPGA.

**Comment by jordens** [comment]
Good. Then I see no urgent need for more LEDs.

Are the 7 extra pins on the FPGA or on the I2C extender?

**Comment by marmeladapk** [comment]
11 on FPGA, 7 on extender, however I would avoid adding more signals to the FPGA just for the sake of it.

**Comment by marmeladapk** [comment]
@jordens from https://github.com/sinara-hw/Kasli/issues/39
> And with the I2C extenders we could add a few (maybe two) more edge LEDs to indicate not SFP-related status but system status like e.g. clock lock, idle kernel running, something else running.

Is this still valid then?

**Comment by jordens** [comment]
Sorting my thoughts: If the extender pins are free and if there is space to place FP LEDs so that it is clear that they are not related to the SFPs, I think we should clean this situation up a bit and put the LEDs that are associated with the SFPs onto the extender as well and add (two) general purpose indicator LEDs on the FPGA pins to the panel.

**Comment by marmeladapk** [comment]
@jordens after adding SFP3 I have one free pin on GPIO expander. What about moving 2 of 3 user leds to FP and adding another one?

**Comment by jordens** [comment]
Good
