### ISSUE TITLE
EEM SI simulation

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Kasli#47]
I'd be interested in seeing the simulated SI of a EEM output from Kasli. Including the FPGA, IDC connectors, 1m ribbon cable, another IDC connector, random patterns on adjacent aggressor channels.

This would be useful for [Fastino](https://github.com/sinara-hw/Fastino/issues/15
) and for the [Urukul SYNC issue](https://github.com/sinara-hw/Urukul/issues/16).

@hartytp did some nice measurements in #14

**Comment by gkasprow** [comment]
I'm afraid it would be hard to find S-models of IDC connectors and assemblies. One can theoretically simulate using connector step model as the geometry but I don't know material characteristics to make it practical.
The easiest way to go would be measurements with a high-speed scope and diff probe.

**Comment by hartytp** [comment]
Closing this, as it seems like nothing is going to happen here, but please do reopen if you have further requests along these lines.
