### ISSUE TITLE
LVDS DCXOs

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Kasli#49]
@marmeladapk AFICT the LVDS Si549 currently has good availability, while the CMOS ones are hard to find. Shall we switch to the LVDS parts (needs RC changes as well)?

**Comment by marmeladapk** [comment]
I made a second variant with LVDS Si549:
![obraz](https://user-images.githubusercontent.com/24512604/66919464-a8e9ea80-f021-11e9-9c42-024380d9c8a3.png)
This the only LVDS Si549 that I found to be available. I also DNPed helper termination in this variant near FPGA.

**Comment by hartytp** [comment]
@WeiDaZhang can you look at this and sign off asap please? (Check terminations, coupling, voltage levels, part numbers, component availability, etc).

**Comment by hartytp** [comment]
@marmeladapk were any changes required for the coupling of the helper PLL to the FPGA?

**Comment by hartytp** [comment]
other than that, LGTM

**Comment by marmeladapk** [comment]
@hartytp I don't think so, at FPGA we'll use LVDS receiver with termination and Si549 has standard common mode output voltage level.

**Comment by hartytp** [comment]
cool

**Comment by WeiDaZhang** [comment]
@hartytp 
They all look right.

**Comment by hartytp** [comment]
Cool.

**Comment by hartytp** [comment]
@marmeladapk for LVDS DCXO, don't you need to DNP R225 (the termination on the helper DCXO at the FPGA)?

**Comment by marmeladapk** [comment]
@hartytp It is DNPed.

**Comment by hartytp** [comment]
Aah, okay, great!
