### ISSUE TITLE
SMA clock in isolation

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Kasli#50]
Question: what's the current thinking on isolating the SMA clock in? IIRC we agreed that using capacitors to float grounds was a bad idea, but how do we feel about isolation transformers?

I ask because the clock in SMA currently goes through a DC isolating transformer, which we're not actually using as such.

What about connecting the input ground of TR1 to the input SMA ground rather than the circuit ground and removing the capacitors that tie the SMA and circuit ground together? We can keep the 0R jumper populated by default so that the two grounds are tied together by default, but this would give the users an easy path (by removing the 0R resistors) to isolate the grounds galvanically.

Thoughts? @jordens

**Comment by jordens** [comment]
Yes. That sounds good to me with the 0r populated.
