### ISSUE TITLE
CMOS Si549 support

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Kasli#56]
With the Si549 connected for CMOS:
Why is there a parallel 51 ohm termination for the FPGA? This is not recommended by the Si549 datasheet.
When the Si549 feeds the ADCLK, it also has a 51 ohm series attenuator, and cannot see a 50 ohm impedance. Why does it appear to be not a problem here while the FPGA would need termination?

**Comment by marmeladapk** [comment]
> Why is there a parallel 51 ohm termination for the FPGA? This is not recommended by the Si549 datasheet.

It terminates the signal, just differently than series termination. BTW I will change this resistor to ~70 Ohm to match trace impedance.

> When the Si549 feeds the ADCLK, it also has a 51 ohm series attenuator, and cannot see a 50 ohm impedance. Why does it appear to be not a problem here while the FPGA would need termination?

ADCLK has built in 50 Ohm resistors. Come to think of it we may change R37 to 30 Ohm. It will still attenuate signal below maximum value.

**Comment by marmeladapk** [comment]
Actually @gkasprow noticed, that series termination is preffered because oscillator may not be able to supply enough current into termination. So I'll change helper termination to 30 ohm series and main also to 30 ohm series.
