### ISSUE TITLE
phanton SFP cages

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Kasli#57]
![image](https://user-images.githubusercontent.com/21218399/69826948-33229280-120d-11ea-8213-620f9229b84d.png)

**Comment by marmeladapk** [comment]
?

**Comment by hartytp** [comment]
I just mean that the SFPs in the rendering aren't in the right place for the quad SFP cage and seem to overlap with the handle/SMA. It's purely a cosmetic issue.

**Comment by marmeladapk** [comment]
Ah, you mean dust covers. I didn't bother positioning them yesterday. And they don't overlap with the handle, it's perspective.
