### ISSUE TITLE
rear power connector

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Kasli#58]
![image](https://user-images.githubusercontent.com/21218399/69826958-446b9f00-120d-11ea-81cb-d0e1b8390085.png)

Will that cause issues getting the EEMs in/out?

**Comment by marmeladapk** [comment]
Again, perspective.
![Zrzut ekranu z 2019-11-29 13-01-02](https://user-images.githubusercontent.com/24512604/69867863-60704e80-12a8-11ea-93c0-6717738790e6.png)
