### ISSUE TITLE
P3V3 to P2V5_LDO caps

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Kasli#60]
What are these for? 
![image](https://user-images.githubusercontent.com/21218399/69827155-0d49bd80-120e-11ea-8c20-7ca762622742.png)

**Comment by marmeladapk** [comment]
For signal integrity purposes when routing.

**Comment by hartytp** [comment]
I believe @WeiDaZhang's question is a repeat of this https://github.com/sinara-hw/Kasli/issues/53#issuecomment-559862512

**Comment by marmeladapk** [comment]
I decided to DNP them for now as high frequency noise could bypass FBs and LDOs.
