### ISSUE TITLE
unused PGs

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Kasli#62]
On the clock page, the LDOs have PGFB resistors populated but the PGs aren't connected. Why bother? 

IC7 even has a PG pull up but the PG isn't connected.

Not a serious issue, just seems a bit odd.

**Comment by marmeladapk** [comment]
It's for fast startup - when PGFB is below 300mV SET current is increased to 2 mA to charge SET capacitor faster. Otherwise startup of those LDOs would take seconds.
