### ISSUE TITLE
unused clock complementary outputs

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Kasli#63]
On IC1 (clock buffer) some of the complementary outputs aren't connected. IIRC it's recommended practice to always bias both halves of LVPECL even when only using one (otherwise it unbalances the output stage).

**Comment by marmeladapk** [comment]
@hartytp In v1.0 we did so to save power. https://github.com/sinara-hw/sinara/issues/204#issue-231061933

**Comment by hartytp** [comment]
Ok, makes sense. However, reading app notes recently, it seems that this is not recommended practice. I can't quantify how bad it is though.

Can we add DNPd termination resistors? When the boards arrive I'll try to find time to do some testing to determine if it's worth populating them in future.

**Comment by marmeladapk** [comment]
I didn't see any significant difference between v1.0 and v1.1 (though in v1.1 there was adclk944).

It might be tricky to add resistors now, I'll check.

**Comment by hartytp** [comment]
Did you look at phase noise/PSRR? Anyway, if this can't easily be done then don't bother. If you can do it easily then it seems worth it.
