### ISSUE TITLE
SMA isolator

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Kasli#69]
I designed and 3D-printed new spacer that eliminates issue with longer SMA connectors
![2020-03-19 21 12 43](https://user-images.githubusercontent.com/4325054/77112046-9ccae480-6a28-11ea-854b-9cdae1bd6852.jpg)
![2020-03-19 21 13 01](https://user-images.githubusercontent.com/4325054/77112056-a05e6b80-6a28-11ea-9a6c-1e421980306f.jpg)
![2020-03-19 21 14 32](https://user-images.githubusercontent.com/4325054/77112062-a2c0c580-6a28-11ea-9b50-31392f347268.jpg)
![2020-03-19 21 14 39](https://user-images.githubusercontent.com/4325054/77112075-a81e1000-6a28-11ea-9929-08dc283a2c33.jpg)
![2020-03-19 21 15 08](https://user-images.githubusercontent.com/4325054/77112080-aa806a00-6a28-11ea-8d27-7e8f7c35ae6d.jpg)
![2020-03-19 21 15 12](https://user-images.githubusercontent.com/4325054/77112085-ad7b5a80-6a28-11ea-8896-1845448abcd3.jpg)
![2020-03-19 21 15 42](https://user-images.githubusercontent.com/4325054/77112095-b0764b00-6a28-11ea-8190-dccf9c0c6189.jpg)
![2020-03-19 21 17 12](https://user-images.githubusercontent.com/4325054/77112101-b2d8a500-6a28-11ea-91e1-9019645a74be.jpg)

**Comment by gkasprow** [comment]
We will do the same for Kasli and other boards.

**Comment by gkasprow** [comment]
The print time is 3mins, print time of batch of 20 is 25mins

**Comment by gkasprow** [comment]
The stl, PRUSA settings and source file:
[MECH.zip](https://github.com/sinara-hw/Kasli/files/4356828/MECH.zip)
use 0.15mm print setting

**Comment by hartytp** [comment]
> The print time is 3mins, print time of batch of 20 is 25mins

How would you convert that into a commercial price (factoring in machine usage etc)?

**Comment by gkasprow** [comment]
both CTI and TS have 3D printers and the price is negligible when printed in batches.
Anyway, I volunteer to print any quantity that is needed.

**Comment by gkasprow** [comment]
One spool of material worth 50$ is sufficient to print thousands of such isolators.

**Comment by hartytp** [comment]
Cool

**Comment by marmeladapk** [comment]
Nothing to do here, closing.
