### ISSUE TITLE
SFP numbers on front panel and schematics are inconsistent

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Kasli#75]
Front panel:
![image](https://user-images.githubusercontent.com/720864/80097588-1f057600-859e-11ea-8ea6-4ad88ad0d972.png)

But schematics says e.g. SFP0 is left bottom:
![image](https://user-images.githubusercontent.com/720864/80097513-04330180-859e-11ea-8bcc-0fd636c4a9f8.png)

**Comment by marmeladapk** [comment]
Turn your Kasli 90 deg ccw ;) I'm pretty sure the markings are correct. In CERN symbol "left bottom" is consistent with manufacturer documentation.

**Comment by sbourdeauducq** [comment]
OK.
