### ISSUE TITLE
Kasli 2.0 premature fan failure

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Kasli#76]
After a few weeks of being continuously powered on, the fan (model pictured) on my Kasli 2.0 no longer spins smoothly, and makes a lot of noise and vibrations.

![image](https://user-images.githubusercontent.com/720864/82725230-1ffd0500-9d0e-11ea-9dd3-bc8533ec6506.png)

**Comment by gkasprow** [comment]
The same happened to the fan on my Xilinx devkit. Isn't it the same company who does them ?

**Comment by sbourdeauducq** [comment]
Replacement part seems to be OK, even though it is the same P/N and manufacturer.

**Comment by gkasprow** [comment]
Maybe it's worth adding the same circuit we use in Thermostat that enables speed control and RPM readout. If we don't need to spin the fan 100% it will significantly prolong its lifetime.
