### ISSUE TITLE
DC bias of CKIN_SMA on Kasli2

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Kasli#82]
On Kasli 2.0, the CKIN_SMA pins do not have an external DC bias, which is required for the FPGA differential input buffer to work properly.
The IN_TERM=UNTUNED_SPLIT_50 feature of the FPGA cannot be used to create the bias, because it is not supported at VCCO=2.5V (it is also uncalibrated, and might not be good enough for impedance matching).

**Comment by gkasprow** [comment]
We can still fix it in current revision. @marmeladapk

**Comment by jordens** [comment]
That would be great.
How feasible is a rework on existing boards? Dc couple and bias the center tap?

**Comment by gkasprow** [comment]
I've noticed that generally, FPGA work without bias due to embedded protection diodes that do some kind of DC recovery. However, it's enough to add a 2x10k resistor divider to any of the diff inputs

**Comment by hartytp** [comment]
> How feasible is a rework on existing boards? Dc couple and bias the center tap?

Or just leave it AC coupled and use a few RCs to add a bias on the FPGA side of the coupling caps. It looks like there should be room to access the capacitor pads on the current layout.

![image](https://user-images.githubusercontent.com/21218399/93608367-729bb480-f9c2-11ea-9ea0-32d7a39ebb51.png)

**Comment by marmeladapk** [comment]
![obraz](https://user-images.githubusercontent.com/24512604/93896826-b14aab00-fcf1-11ea-92df-9a8240b04507.png)

I removed AC couple and added bias to center tap.

**Comment by jordens** [comment]
Does the balun bypass work without a bias and ac-coupled on the `_p` signal? Can be scrapped IMO.

**Comment by marmeladapk** [comment]
If you remove balun then you can solder 0R between 1st and 2nd pins giving _P signal DC bias.

**Comment by hartytp** [comment]
> If you remove balun then you can solder 0R between 1st and 2nd pins giving _P signal DC bias. I'll add a note about that.

Which pads are you using for that?

**Comment by sbourdeauducq** [comment]
I'm not sure if a single-ended signal is a good idea since we lose the comparator present in FPGA differential inputs, and a sine wave into a CMOS input buffer may be noisy.

**Comment by sbourdeauducq** [comment]
> However, it's enough to add a 2x10k resistor divider to any of the diff inputs

What are easy soldering locations to do this?

**Comment by marmeladapk** [comment]
I'd say the best one is under the FPGA. There are pads for termination resistor there:

![obraz](https://user-images.githubusercontent.com/24512604/93997320-916bc380-fd93-11ea-8084-68421dc786a7.png)

![Przechwytywanie1](https://user-images.githubusercontent.com/24512604/93997451-b5c7a000-fd93-11ea-90a0-9e90633257f9.jpg)

**Comment by sbourdeauducq** [comment]
@marmeladapk thank you

**Comment by SingularitySurfer** [comment]
Hi, I did some further debugging because it still didn't work after the mod. In addition, the sl5324 needs to be configured for CKIN1 (currently it's still set to CKIN2 in artiq). But even with this change, the si5324 does not lock, even tho we verified there is a clocksignal at CKIN1 coming from the FPGA. Any ideas?

**Comment by SingularitySurfer** [comment]
The LVDS seems to be happy without external bias with a 0dBm clock input signal.

**Comment by sbourdeauducq** [comment]
Hmm. I would worry about noise or long-term effects... Are negative voltages/currents within FPGA ratings?

**Comment by SingularitySurfer** [comment]
Kinda funny: With external bias to 1.25V (which is 50mV off the 1.2V LVDS center) it's fine until ~ -8dBm.
With no external bias until ~ -14dBm, however once it loses signal you have to go quite a bit higher before it works again.
And ofc. thats just a one off try and not according to spec.

**Comment by hartytp** [comment]
> With no external bias until ~ -14dBm, however once it loses signal you have to go quite a bit higher before it works again.
And ofc. thats just a one off try and not according to spec.

Sounds like you're baising by rectifying the input clock through the FPGA ESD capacitors, hence the hysteresis

**Comment by jordens** [comment]
Long term this is completely harmless (~50 nC per boot) and I don't see how the rectification (assuming you mean ESD *diodes*?) explains the hysteresis. As Greg days, it explains the self-biasing. I'd look at the si5324 and its lock/LOS hysteresis. The V,T stability of the self-biasing might be interesting though, but even that would be common mode.
