### ISSUE TITLE
Kasli 2.0 12V input short circuit

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Kasli#87]
I have <s>two</s> <s>three</s> four Kasli 2.0 from TS and Creotech that died in exactly the same way: after a few weeks, a short circuit developed on the 12V input. No burned components or other visible damage. Both failures occurred while boards were inside metallic chassis (ESD is very unlikely).

I'm opening this issue here to collect information about this problem.

**Comment by kaolpr** [comment]
Have you tried disconnecting the fan? As problems with these have already been reported (#76) maybe it's generating not only vibrations...

**Comment by sbourdeauducq** [comment]
This is on Technosystem boards. They came without fan, and we fitted them with another fan model that we used many times before on Kasli 1 without such an issue.
Also, this is a hard short that can be measured with a DMM, without power applied to the board. The MOSFET that controls the fan cannot have voltage above threshold on its gate.

**Comment by gkasprow** [comment]
This could be related to the input protection diode.
If you use a power supply with an output voltage that exceeds 12V significantly, you may heat the D1. It may burn after some time and get shorted.
Just remove D1 and see what happenes.

**Comment by sbourdeauducq** [comment]
The power supply is the same AKM65US12 that we have been using before on many Kasli 1.1 without problems, and every time I measured their output it was well below the 13.3V breakdown voltage of the SMBJ12A used on all Kaslis. So this scenario does not sound likely.

**Comment by sbourdeauducq** [comment]
One of the boards was actually from Creotech.

> Just remove D1 and see what happenes.

Still the same.

**Comment by sbourdeauducq** [comment]
> Have you tried disconnecting the fan?

For good measure, I also tried that - still the same, as expected.

**Comment by maciejprzybysz** [comment]
We have just checked Kasli v2.0 sent to Technosystem. We found that the cause of the short circuit is C3 capacitor on the TLV62150 DCDC converter input. In the project 10uF / 6.3V capacitor was used. This converter is powered by 12V, so the capacitor should be rated at least 16V. This problem affects all of the Kasli boards manufactured in accordance with [v2.0rc2](https://github.com/sinara-hw/Kasli/releases/tag/v2.0rc2) and [v2.0.1](https://github.com/sinara-hw/Kasli/releases/tag/v2.0.1) release documentation.

![C3_kasli](https://user-images.githubusercontent.com/48446953/104948733-0eafe980-59be-11eb-92d5-53bb43a1ae96.png)

We removed the capacitor from the board. It looks like the short circuit is gone and the board is working fine. Unfortunately, there are no suitable 10uF capacitors in 0402 case on the market, so a design change is required.

**Comment by dtcallcock** [comment]
Would stacking 2x 4.7uF on top of each other be a reasonable way of patching existing boards?

**Comment by sbourdeauducq** [comment]
> Unfortunately, there are no suitable 10uF capacitors in 0402 case on the market

What makes a capacitor suitable here besides the obvious - X5R dielectric?

> Would stacking 2x 4.7uF on top of each other be a reasonable way of patching existing boards?

Or maybe try to fit a 0603 if the footprint happens to be large enough...

**Comment by sbourdeauducq** [comment]
Patch with 0805 capacitor (Murata GRM21BR61C106KE15K) and solder bridges
![image](https://user-images.githubusercontent.com/720864/104991714-597f3f00-5a5a-11eb-9067-e6105acf9ee0.png)

Board works again!

**Comment by akaminska** [comment]
Thank you all very much for your help with understanding this issue! Attached is a description of a recommended patch
[Kasli_v2_patch_210122.pdf](https://github.com/sinara-hw/Kasli/files/5866415/Kasli_v2_patch_210122.pdf)
