### ISSUE TITLE
CLK_SEL unrouted

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/Kasli#94]
On Kasli v2.0 PCB why is CLK_SEL not routed to the FPGA? Currently it looks like it requires a hardware change to choose between OSC1 (Main_DCXO) and Si5424.

**Comment by gkasprow** [comment]
these lines are routed to the I2C extender (IC25), the same applies to DCXO OE lines.

**Comment by jbqubit** [comment]
Got it. Thanks @gkasprow. ![image](https://user-images.githubusercontent.com/20543958/142274318-49f6eabf-b3e4-4b9a-873f-0757cd79e52f.png)

**Comment by sbourdeauducq** [comment]
Current firmware handles this just fine already.
