### ISSUE TITLE
EEPROM availability

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/Kasli#97]
add footprint for 24AA02E48T-I/SN

**Comment by filipswit** [comment]
There is 24AA025E48-I/SN already, they are footprint compatible.

**Comment by gkasprow** [comment]
24AA025E48 has 16byte page while 24AA02E48 has 8byte page.

**Comment by marmeladapk** [comment]
24AA02E48 takes 8 I2C addresses (last 3 bits of address are "don't care") and clashes with SFP3 address space.
